COLORS:
  EMBED_COLOR: "Purple"

CHANNELS:
  WELCOME_CHANNEL: ""
  MODS_ONLY_CHANNEL: ""
  GIVEAWAY_CHANNEL: ""

ROLES:
  JOINING_ROLE: ""

MESSAGES:
  WELCOME_MESSAGE: "Bienvenue ${member} sur Hepheria\n \nNous sommes maintenant **${memberCount}** sur le serveur !"

IMAGES:
  WELCOME_IMAGE: "https://media.discordapp.net/attachments/1222577382926581883/1232289893032525847/Plan_de_travail_3.png?ex=6628eae5&is=66279965&hm=a51f16d7d20802037c5e3673edb854f2bc408489793770a46cebaca431bdc650&=&format=webp&quality=lossless&width=1440&height=471"